nodeLinker: node-modules

packageExtensions:
  "@better-auth/expo@*":
    dependencies:
      "@better-auth/core": "^1.6.15"
    peerDependenciesMeta:
      "@better-auth/core":
        optional: true
